In [1]:
#本部分用于测试那些运行起来非常快的指标做快速测试
import cfe
import scanpy as sc

cfe.settings.backend = "python_function"
cfe.logger.setLevel("DEBUG")
import pandas as pd
import numpy as np
from cfe.data import FateAnnData
from cfe.metric.metric_correlation_v2 import calculate_correlation
from cfe.metric.metric_position_predict_v3 import calculate_position_predict
from cfe.metric.metric_featureimp_v3 import (
    calculate_overall_feature_importance,
    calculate_featureimp_cor,
    calculate_featureimp_enrichment,
    fi_ranger_rf_tiny
)
from cfe.metric.cluster_metric_v2 import calculate_mapping_branches, calculate_mapping_milestones,calculate_mapping
from cfe.metric._topology_metric.metric_him import calculate_him
from cfe.metric.topology_metric import calc_isomorphic, calculate_edge_flip

[2025年04月26日 22时18分56秒] INFO
                                          _____     _ _ ______    _       ______            _
                                         / ____|   | | |  ____|  | |     |  ____|          | |
                                        | |     ___| | | |__ __ _| |_ ___| |__  __  ___ __ | | ___  _ __ ___ _ __
                                        | |    / _ \ | |  __/ _` | __/ _ \  __| \ \/ / '_ \| |/ _ \| '__/ _ \ '__|
                                        | |___|  __/ | | | | (_| | ||  __/ |____ >  <| |_) | | (_) | | |  __/ |
                                         \_____\___|_|_|_|  \__,_|\__\___|______/_/\_\ .__/|_|\___/|_|  \___|_|
                                                                                     | |
                                                                                     |_|

In [2]:
# 读取scvelo的pancreas数据
adata = sc.read_h5ad("/home/huang/PyCode/scRNA/data/Pancreas/endocrinogenesis_day15.h5ad")
fadata = cfe.data.FateAnnData.from_anndata(adata)
fadata.layers["expression"] = fadata.layers["spliced"]
fadata.layers["count"] = fadata.layers["spliced"]

basis = "umap"

sc.pp.subsample(fadata, n_obs=500)

fadata

[2025年04月26日 22时18分57秒] DEBUG    Create a FateAnnData object from an existing AnnData object.
                        DEBUG    Create a FateAnnData object from an existing AnnData object.

AnnData object with n_obs × n_vars = 500 × 27998
    obs: 'clusters_coarse', 'clusters', 'S_score', 'G2M_score'
    var: 'highly_variable_genes'
    uns: 'clusters_coarse_colors', 'clusters_colors', 'day_colors', 'neighbors', 'pca', 'cfe'
    obsm: 'X_pca', 'X_umap'
    layers: 'spliced', 'unspliced', 'expression', 'count'

In [3]:
# 手动添加参考里程碑
milestone_network = pd.DataFrame(
    data=[
        ["Ductal", "Ngn3 low EP"],
        ["Ngn3 low EP", "Ngn3 high EP"],
        ["Ngn3 high EP", "Pre-endocrine"],
        ["Pre-endocrine", "Alpha"],
        ["Pre-endocrine", "Beta"],
        ["Pre-endocrine", "Delta"],
        ["Pre-endocrine", "Epsilon"],
        ],
    columns=["from", "to"]
)

fadata.add_trajectory_mannually(milestone_network)

                        DEBUG    FateAnnData add_trajectory

In [4]:
cluster_key = "milestone_color"
fadata.group_onto_nearest_milestones(cluster_key=cluster_key) # new cluster color

In [5]:
prior_information = {
    "start_id": fadata.obs.index[0],
    "groups_id": fadata.obs[cluster_key].tolist()
}
parameters = {"filter_features": False, "connectivity_cutoff": 0.3}
fadata.add_prior_information(**prior_information)  # add prior information to fadata

In [6]:
method_name_list = ["comp1", "state_comp","paga","cluster_mst","projection_mst"]
for method_name in method_name_list:
        method = cfe.method.FateMethod(method_name=method_name)
        method.infer_trajectory(fadata)

                        DEBUG    FunctionBackend __init__
                        INFO     Loaded function: <function cf_comp1 at 0x78b040bf3490> from
                                 /home/mhn/Code/CellFateExplorer/cfe/method/function/cf_comp1.py
                        INFO     method_backend: <cfe.method.fate_function_backend.FunctionBackend object at
                                 0x78b040335e10>
                        DEBUG    FateAnnData add_trajectory
                        DEBUG    FunctionBackend __init__
                        INFO     Loaded function: <function cf_state_comp at 0x78b040bf3880> from
                                 /home/mhn/Code/CellFateExplorer/cfe/method/function/cf_state_comp.py
                        INFO     method_backend: <cfe.method.fate_function_backend.FunctionBackend object at
                                 0x78b040335990>
[2025年04月26日 22时18分58秒] DEBUG    FateAnnData add_trajectory
                        DEBUG    FunctionBackend __init__
                        INFO     Loaded function: <function cf_paga at 0x78b02eebeb90> from
                                 /home/mhn/Code/CellFateExplorer/cfe/method/function/cf_paga.py
                        INFO     method_backend: <cfe.method.fate_function_backend.FunctionBackend object at
                                 0x78b02eec3c70>
Normalized count data: X, spliced, unspliced.
Logarithmized X.
[2025年04月26日 22时19分00秒] DEBUG    FateAnnData add_trajectory_branch
                        DEBUG    FateAnnData add_trajectory
                        DEBUG    FunctionBackend __init__
                        INFO     Loaded function: <function cf_cluster_mst at 0x78b02b561a20> from
                                 /home/mhn/Code/CellFateExplorer/cfe/method/function/cf_cluster_mst.py
                        INFO     method_backend: <cfe.method.fate_function_backend.FunctionBackend object at
                                 0x78b02eec3ca0>
[2025年04月26日 22时19分01秒] DEBUG    FateAnnData add_trajectory
                        DEBUG    FunctionBackend __init__
                        INFO     Loaded function: <function cf_projection_mst at 0x78b027b00790> from
                                 /home/mhn/Code/CellFateExplorer/cfe/method/function/cf_projection_mst.py
                        INFO     method_backend: <cfe.method.fate_function_backend.FunctionBackend object at
                                 0x78b025d4f7c0>
                        DEBUG    FateAnnData add_trajectory

In [7]:
parsed_model_name_list = fadata.get_all_model_name() # 解析后的模型名称
model_name_list = fadata.get_all_model_name(parse=False)
parsed_model_name_list, model_name_list

                        WARNING  'ref' is not a valid random_time_string, don't need parse

(['ref',
  'comp1-python_function',
  'state_comp-python_function',
  'paga-python_function',
  'cluster_mst-python_function',
  'projection_mst-python_function'],
 ['ref',
  '20250426_221857__comp1-python_function__JeUlnOCx2Q',
  '20250426_221857__state_comp-python_function__FzvtuBBQP4',
  '20250426_221858__paga-python_function__vXS1aE6b7Z',
  '20250426_221900__cluster_mst-python_function__QteUeXEuZa',
  '20250426_221901__projection_mst-python_function__eyjIJd2t6r'])

In [8]:
new_fadata = cfe.data.FateAnnData(
        X=fadata.X,
        obs=fadata.obs,
        uns=fadata.uns
    )
for i in model_name_list: 
    new_fadata.model_name = i
    new_fadata.milestone_wrapper = fadata.trajectory_history_dict[i]['milestone_wrapper']
    new_fadata.add_waypoints()
    # 使用单引号避免冲突
    print(f"{i}'s milestone_network is:\n {new_fadata.milestone_wrapper['milestone_network']}")
    print(f"{i}'s progressions is:\n {new_fadata.milestone_wrapper['progressions']}")

    

prior_information = {
    "start_id": fadata.obs.index[0],
    "groups_id": fadata.obs[cluster_key].tolist()
}
parameters = {"filter_features": False, "connectivity_cutoff": 0.3}
new_fadata.add_prior_information(**prior_information)  # add prior information to fadata

                        DEBUG    FateAnnData add_waypoints
ref's milestone_network is:
             from             to    length  directed
0         Ductal    Ngn3 low EP  1.671231      True
1    Ngn3 low EP   Ngn3 high EP  8.994165      True
2   Ngn3 high EP  Pre-endocrine  6.586894      True
3  Pre-endocrine          Alpha  6.210582      True
4  Pre-endocrine           Beta  6.141845      True
5  Pre-endocrine          Delta  3.911559      True
6  Pre-endocrine        Epsilon  4.122478      True
ref's progressions is:
              cell_id           from           to  percentage
0   AGCGGTCGTGTATGGG         Ductal  Ngn3 low EP    0.199266
1   TTCTCCTCACAGACTT         Ductal  Ngn3 low EP    0.000000
2   CAGCAGCAGACACGAC         Ductal  Ngn3 low EP    1.000000
3   CGTGTAATCTTTAGTC         Ductal  Ngn3 low EP    0.000000
4   CTGCTGTGTCTTTCAT         Ductal  Ngn3 low EP    0.139954
..               ...            ...          ...         ...
13  CCTTACGAGAGATGAG  Pre-endocrine      Epsilon    1.000000
14  TGTCCCACATTATCTC  Pre-endocrine      Epsilon    0.826879
15  TAAGCGTGTTTGGGCC  Pre-endocrine      Epsilon    1.000000
16  AGAATAGCAATCACAC  Pre-endocrine      Epsilon    1.000000
17  ATCATCTAGATCCCGC  Pre-endocrine      Epsilon    0.861431

[500 rows x 4 columns]
                        DEBUG    FateAnnData add_waypoints
20250426_221857__comp1-python_function__JeUlnOCx2Q's milestone_network is:
               from             to  length  directed
0  milestone_begin  milestone_end       1     False
20250426_221857__comp1-python_function__JeUlnOCx2Q's progressions is:
               cell_id             from             to  percentage
0    AGCGGTCGTGTATGGG  milestone_begin  milestone_end    0.105841
1    GTCCTCACATGACATC  milestone_begin  milestone_end    0.214790
2    CGTAGGCCACAAGACG  milestone_begin  milestone_end    0.192776
3    TTCTCCTCACAGACTT  milestone_begin  milestone_end    0.100142
4    GTTTCTATCGTTACGA  milestone_begin  milestone_end    0.351206
..                ...              ...            ...         ...
495  AGCGGTCTCCTCTAGC  milestone_begin  milestone_end    0.123679
496  CATCGAAAGATGTTAG  milestone_begin  milestone_end    0.039718
497  AAAGCAACACGGTAAG  milestone_begin  milestone_end    0.122310
498  GAACATCTCACAAACC  milestone_begin  milestone_end    0.158171
499  TGAAAGAGTCTAAAGA  milestone_begin  milestone_end    0.451216

[500 rows x 4 columns]
[2025年04月26日 22时19分02秒] DEBUG    FateAnnData add_waypoints
20250426_221857__state_comp-python_function__FzvtuBBQP4's milestone_network is:
               from      to  length  directed
0  milestone_begin  comp_1       1      True
1  milestone_begin  comp_2       1      True
20250426_221857__state_comp-python_function__FzvtuBBQP4's progressions is:
               cell_id             from      to  percentage
0    AGCGGTCGTGTATGGG  milestone_begin  comp_1    0.026050
1    GTCCTCACATGACATC  milestone_begin  comp_1    0.101700
2    CGTAGGCCACAAGACG  milestone_begin  comp_1    0.082936
3    TTCTCCTCACAGACTT  milestone_begin  comp_1    0.023272
4    GTTTCTATCGTTACGA  milestone_begin  comp_1    0.198293
..                ...              ...     ...         ...
995  AGCGGTCTCCTCTAGC  milestone_begin  comp_2    0.088270
996  CATCGAAAGATGTTAG  milestone_begin  comp_2    0.036003
997  AAAGCAACACGGTAAG  milestone_begin  comp_2    0.087753
998  GAACATCTCACAAACC  milestone_begin  comp_2    0.100830
999  TGAAAGAGTCTAAAGA  milestone_begin  comp_2    0.148118

[1000 rows x 4 columns]
                        DEBUG    FateAnnData add_waypoints
20250426_221858__paga-python_function__vXS1aE6b7Z's milestone_network is:
   from to    length  directed
0    1  2  0.076190      True
1    2  5  0.138634      True
2    2  2  0.052612      True
3    3  2  0.121388      True
4    2  6  0.075096      True
5    4  2  0.496133      True
6    2  2  0.272787      True
7    2  2  0.166266      True
20250426_221858__paga-python_function__vXS1aE6b7Z's progressions is:
               cell_id from to  percentage
0    AGCGGTCGTGTATGGG    1  2    0.884317
1    GTCCTCACATGACATC    2  5    0.558875
2    CGTAGGCCACAAGACG    2  5    0.349715
3    TTCTCCTCACAGACTT    1  2    0.745391
4    GTTTCTATCGTTACGA    2  2    0.629164
..                ...  ... ..         ...
495  AGCGGTCTCCTCTAGC    2  6    0.592451
496  CATCGAAAGATGTTAG    1  2    0.000000
497  AAAGCAACACGGTAAG    1  2    0.594573
498  GAACATCTCACAAACC    4  2    0.622963
499  TGAAAGAGTCTAAAGA    3  2    0.712162

[500 rows x 4 columns]
[2025年04月26日 22时19分03秒] DEBUG    FateAnnData add_waypoints
20250426_221900__cluster_mst-python_function__QteUeXEuZa's milestone_network is:
   from  to      length  directed
0   M0  M2    8.659473     False
1   M0  M1  199.163254     False
2   M2  M4  125.609268     False
3   M3  M6   53.101070     False
4   M4  M7   77.331985     False
5   M5  M6   49.940002     False
6   M5  M7   64.717003     False
20250426_221900__cluster_mst-python_function__QteUeXEuZa's progressions is:
               cell_id from  to  percentage
0    AAACCTGAGCCTTGAT   M3  M6           1
1    AAACCTGGTAAGTGGC   M5  M6           0
2    AAACGGGAGTAGCGGT   M0  M2           1
3    AAACGGGCACTGTGTA   M3  M6           0
4    AAACGGGCAGTTCCCT   M3  M6           1
..                ...  ...  ..         ...
495  TTTCCTCTCCACGTTC   M3  M6           1
496  TTTGCGCAGACAGACC   M3  M6           1
497  TTTGCGCAGCAACGGT   M0  M2           0
498  TTTGGTTCACGAAGCA   M5  M6           0
499  TTTGTCAAGTGACATA   M4  M7           1

[500 rows x 4 columns]
                        DEBUG    FateAnnData add_waypoints
20250426_221901__projection_mst-python_function__eyjIJd2t6r's milestone_network is:
   from  to      length  directed
0   M0  M2  191.861237     False
1   M1  M2  213.235397     False
2   M2  M7  216.239410     False
3   M3  M6  105.305748     False
4   M4  M7  446.503540     False
5   M5  M7   80.632706     False
6   M5  M6   98.157890     False
20250426_221901__projection_mst-python_function__eyjIJd2t6r's progressions is:
               cell_id from  to  percentage
0    AGCGGTCGTGTATGGG   M3  M6    0.907630
1    GTCCTCACATGACATC   M2  M7    0.599599
2    CGTAGGCCACAAGACG   M2  M7    0.902424
3    TTCTCCTCACAGACTT   M3  M6    0.627694
4    GTTTCTATCGTTACGA   M1  M2    0.509636
..                ...  ...  ..         ...
495  AGCGGTCTCCTCTAGC   M5  M6    0.459679
496  CATCGAAAGATGTTAG   M3  M6    0.000000
497  AAAGCAACACGGTAAG   M5  M6    0.573796
498  GAACATCTCACAAACC   M5  M7    0.865900
499  TGAAAGAGTCTAAAGA   M1  M2    0.623208

[500 rows x 4 columns]

In [9]:
metrics = cfe.metric.metrics
metrics

,metric_id,plotmath,latex,html,long_name,category,type,perfect,worst,symmetric
0,correlation,cor[dist],\mathit{cor}_{\textrm{dist}},cor<sub>dist</sub>,Geodesic distance correlation,cell positions,specific,1,0.0,True
1,rf_mse,MSE[rf],\mathit{MSE}_{\textit{rf}},MSE<sub>rf</sub>,Random Forest MSE,neighbourhood,specific,0,0.3,False
2,rf_nmse,NMSE[rf],\mathit{NMSE}_{\textit{rf}},NMSE<sub>rf</sub>,Random Forest Normalised MSE,neighbourhood,specific,1,0.0,False
3,rf_rsq,R[rf]^2,R^{2}_{rf},R<sup>2</sup><sub>rf</sub>,Random Forest R²,neighbourhood,specific,1,0.0,False
4,lm_nmse,NMSE[lm],\mathit{NMSE}_{\textit{lm}},NMSE<sub>lm</sub>,Linear regression Normalised MSE,neighbourhood,specific,1,0.0,False
5,lm_mse,MSE[lm],\mathit{MSE}_{\textit{lm}},MSE<sub>lm</sub>,Linear regression MSE,neighbourhood,specific,0,0.3,False
6,lm_rsq,R[lm]^2,R^{2}_{lm},R<sup>2</sup><sub>lm</sub>,Linear regression R²,neighbourhood,specific,1,0.0,False
7,edge_flip,edgeflip,\textrm{edgeflip},edgeflip,Edge flip,topology,specific,1,0.0,True
8,him,HIM,\textrm{HIM},HIM,Hamming-Ipsen-Mikhailov similarity,topology,specific,1,0.0,True
9,isomorphic,isomorphic,\textrm{isomorphic},Isomorphic,isomorphic,topology,specific,1,0.0,True
10,featureimp_cor,cor[features],\mathit{cor}_{\textrm{features}},cor<sub>features</sub>,Feature importance correlation,features,application,1,0.0,True
11,featureimp_wcor,wcor[features],\mathit{wcor}_{\textrm{features}},wcor<sub>features</sub>,Feature importance weighted correlation,features,application,1,0.0,False
12,featureimp_ks,ks[features],\mathit{ks}_{\textrm{features}},ks<sub>feature</sub>,Feature importance enrichment ks,features,application,1,0.0,True
13,featureimp_wilcox,wilcox[features],\mathit{wilcox}_{\textrm{features}},wilcox<sub>feature</sub>,Feature importance enrichment wilcox,features,application,1,0.0,True
14,F1_branches,F1[branches],\mathit{F1}_{\textit{branches}},F1<sub>branches</sub>,Overlap between the branches,branch assignment,specific,1,0.0,True
15,F1_milestones,F1[milestones],\mathit{F1}_{\textit{milestones}},F1<sub>milestones</sub>,Overlap between the milestones,branch assignment,specific,1,0.0,True
16,harm_mean,mean[harmonic],\mathit{mean}_{\textit{harmonic}},mean<sub>harmonic</sub>,Harmonic mean,average,overall,1,0.0,False
17,geom_mean,mean[geometric],\mathit{mean}_{\textit{geometric}},mean<sub>geometric</sub>,Geometric mean,average,overall,1,0.0,False
18,arith_mean,mean[arithmetic],\mathit{mean}_{\textit{arithmetic}},mean<sub>arithmetic</sub>,Arithmetic mean,average,overall,1,0.0,False

试试随机森林那些比较慢的指标表现如何

In [10]:
for i in model_name_list:
    print(calculate_featureimp_cor(
            new_fadata,
            "ref",
            i,
            new_fadata.X,
            fi_ranger_rf_tiny()
    ))
    print(calculate_featureimp_enrichment(
            new_fadata,
            "ref",
            i,
            new_fadata.X,
            fi_ranger_rf_tiny()
    ))

{'featureimp_cor': 1.0, 'featureimp_wcor': 1.0}
{'featureimp_ks': 1.0, 'featureimp_wilcox': 1.0}
{'featureimp_cor': 0.6855767779480869, 'featureimp_wcor': 0.7340473938525278}
{'featureimp_ks': 0.0, 'featureimp_wilcox': 0.0}
{'featureimp_cor': 0.7131458304223923, 'featureimp_wcor': 0.7472826417331392}
{'featureimp_ks': 0.0, 'featureimp_wilcox': 0.0}
{'featureimp_cor': 0.8626379316058566, 'featureimp_wcor': 0.9065197807181213}
{'featureimp_ks': 0.0, 'featureimp_wilcox': 0.0}
{'featureimp_cor': 0.9337801122232439, 'featureimp_wcor': 0.9501120453861222}
{'featureimp_ks': 0.0, 'featureimp_wilcox': 0.0}
{'featureimp_cor': 0.8679049272267945, 'featureimp_wcor': 0.8941975748626069}
{'featureimp_ks': 0.0, 'featureimp_wilcox': 0.0}

In [11]:
for i in model_name_list:
    print(calculate_position_predict(
        new_fadata,
        ref_model='ref',
        pred_model=i,
        metrics=["rf_mse","rf_rsq","rf_nmse","lm_mse","lm_rsq","lm_nmse"]
    ))

{'summary': {'rf_mse': 7.213010917162967e-05, 'rf_rsq': 0.9982256581527431, 'rf_nmse': 0.9990810714485362, 'lm_mse': 0.0, 'lm_rsq': 1.0, 'lm_nmse': 1.0}, 'rf_mses': {'Alpha': 1.8420746824911923e-05, 'Beta': 2.0956468787961036e-05, 'Delta': 0.00035783022419503234, 'Ductal': 0.00010619117126407761, 'Epsilon': 1.815906007833832e-05, 'Ngn3 high EP': 1.893423008471104e-05, 'Ngn3 low EP': 2.9246195611453932e-05, 'Pre-endocrine': 7.302776526551191e-06}, 'rf_rsqs': {'Alpha': 0.9998242692165579, 'Beta': 0.9998066664690053, 'Delta': 0.9882998366348373, 'Ductal': 0.9990724160998429, 'Epsilon': 0.9994652658208695, 'Ngn3 high EP': 0.9997470108808021, 'Ngn3 low EP': 0.9997158107732999, 'Pre-endocrine': 0.9998739893267301}, 'lm_rsqs': {'Alpha': 1.0, 'Beta': 1.0, 'Delta': 1.0, 'Ductal': 1.0, 'Epsilon': 1.0, 'Ngn3 high EP': 1.0, 'Ngn3 low EP': 1.0, 'Pre-endocrine': 1.0}}
{'summary': {'rf_mse': 0.06732725973111518, 'rf_rsq': 0.15447800416805574, 'rf_nmse': 0.1422591485127923, 'lm_mse': 0.0675195347361532, 'lm_rsq': 0.10750386532869974, 'lm_nmse': 0.1398095890446116}, 'rf_mses': {'Alpha': 0.10361874695650976, 'Beta': 0.09888877156449984, 'Delta': 0.04853247089811335, 'Ductal': 0.06884351129829885, 'Epsilon': 0.038233627062701905, 'Ngn3 high EP': 0.052143410294354084, 'Ngn3 low EP': 0.08616573386503044, 'Pre-endocrine': 0.04219180590941323}, 'rf_rsqs': {'Alpha': 0.01149482401341051, 'Beta': 0.08770339241127623, 'Delta': 0.0, 'Ductal': 0.39864932319297264, 'Epsilon': 0.0, 'Ngn3 high EP': 0.30328746490738945, 'Ngn3 low EP': 0.16271594430682768, 'Pre-endocrine': 0.2719730845125695}, 'lm_rsqs': {'Alpha': 0.1145475869600645, 'Beta': 0.34425480469514735, 'Delta': 0.017188255471725533, 'Ductal': 0.18192436343547547, 'Epsilon': 0.0, 'Ngn3 high EP': 0.048966054061725384, 'Ngn3 low EP': 0.15314985800545966, 'Pre-endocrine': 0.0}}
{'summary': {'rf_mse': 0.0550110650454127, 'rf_rsq': 0.2931786734831331, 'rf_nmse': 0.2991659253367196, 'lm_mse': 0.06527072639885005, 'lm_rsq': 0.12876196956666325, 'lm_nmse': 0.1684591254400235}, 'rf_mses': {'Alpha': 0.08530140471609876, 'Beta': 0.06305821705204269, 'Delta': 0.03494950375428545, 'Ductal': 0.0708229268404761, 'Epsilon': 0.01862070060791607, 'Ngn3 high EP': 0.04611010704708105, 'Ngn3 low EP': 0.08168841118861046, 'Pre-endocrine': 0.03953724915679102}, 'rf_rsqs': {'Alpha': 0.18623914535290453, 'Beta': 0.41825753736206883, 'Delta': 0.0, 'Ductal': 0.38135905351435384, 'Epsilon': 0.45167178193943214, 'Ngn3 high EP': 0.3839012563080876, 'Ngn3 low EP': 0.20622269253498093, 'Pre-endocrine': 0.31777792085323686}, 'lm_rsqs': {'Alpha': 0.16864673826863075, 'Beta': 0.42608076010149165, 'Delta': 0.01876470438366984, 'Ductal': 0.2002257665651287, 'Epsilon': 0.007644572608144107, 'Ngn3 high EP': 0.056718871150568395, 'Ngn3 low EP': 0.15201434345567266, 'Pre-endocrine': 0.0}}
{'summary': {'rf_mse': 0.02334280063209066, 'rf_rsq': 0.5993330001967365, 'rf_nmse': 0.7026156452790785, 'lm_mse': 0.03736982419380719, 'lm_rsq': 0.4545474512905229, 'lm_nmse': 0.5239131229766967}, 'rf_mses': {'Alpha': 0.006645303363326015, 'Beta': 0.05252273968433665, 'Delta': 0.02814327868926109, 'Ductal': 0.01290794159986554, 'Epsilon': 0.030009663850907912, 'Ngn3 high EP': 0.01113974528805272, 'Ngn3 low EP': 0.025344835562243498, 'Pre-endocrine': 0.020028897018731884}, 'rf_rsqs': {'Alpha': 0.9366049391293457, 'Beta': 0.5154523968979358, 'Delta': 0.07978438926896358, 'Ductal': 0.8872486415803064, 'Epsilon': 0.11629826124965836, 'Ngn3 high EP': 0.8511566440301368, 'Ngn3 low EP': 0.7537208150089922, 'Pre-endocrine': 0.6543979144085526}, 'lm_rsqs': {'Alpha': 0.6670992160292146, 'Beta': 0.25861828288983957, 'Delta': 0.0465897236201831, 'Ductal': 0.6358542508006204, 'Epsilon': 0.05604813770759587, 'Ngn3 high EP': 0.7199967447566598, 'Ngn3 low EP': 0.6329210105832827, 'Pre-endocrine': 0.6192522439367873}}
{'summary': {'rf_mse': 0.008614230587457828, 'rf_rsq': 0.8895572594907263, 'rf_nmse': 0.8902557818556439, 'lm_mse': 0.008617928539613094, 'lm_rsq': 0.8895034993765638, 'lm_nmse': 0.8902086704086151}, 'rf_mses': {'Alpha': 0.004749032524021772, 'Beta': 0.009776596321238219, 'Delta': 0.0035853334869543688, 'Ductal': 0.01217254444372523, 'Epsilon': 0.0002417288878052638, 'Ngn3 high EP': 0.00934835992638335, 'Ngn3 low EP': 0.014411789101686192, 'Pre-endocrine': 0.014628460007848221}, 'rf_rsqs': {'Alpha': 0.9546950395675553, 'Beta': 0.9098061840942929, 'Delta': 0.8827684620260293, 'Ductal': 0.8936723635727937, 'Epsilon': 0.9928817517076841, 'Ngn3 high EP': 0.8750921831444934, 'Ngn3 low EP': 0.8599587018227479, 'Pre-endocrine': 0.7475833899902133}, 'lm_rsqs': {'Alpha': 0.9546223420622698, 'Beta': 0.9096837068993923, 'Delta': 0.8827248315490116, 'Ductal': 0.8936822868347424, 'Epsilon': 0.9929542682968949, 'Ngn3 high EP': 0.8751389149477625, 'Ngn3 low EP': 0.8600503908832103, 'Pre-endocrine': 0.7471712535392261}}
{'summary': {'rf_mse': 0.049952984393079644, 'rf_rsq': 0.3541399352884894, 'rf_nmse': 0.36360523896614505, 'lm_mse': 0.040204957777326855, 'lm_rsq': 0.4692166956374513, 'lm_nmse': 0.48779387642307115}, 'rf_mses': {'Alpha': 0.06010522087812482, 'Beta': 0.06444668832765714, 'Delta': 0.03375165571154104, 'Ductal': 0.06312314832944468, 'Epsilon': 0.007916974520221417, 'Ngn3 high EP': 0.05009923893092148, 'Ngn3 low EP': 0.07014071903624033, 'Pre-endocrine': 0.050040229410486185}, 'rf_rsqs': {'Alpha': 0.426606442492683, 'Beta': 0.4054482202430746, 'Delta': 0.0, 'Ductal': 0.4486169102324692, 'Epsilon': 0.7668669604591338, 'Ngn3 high EP': 0.3306005962262102, 'Ngn3 low EP': 0.31843317442303254, 'Pre-endocrine': 0.1365471782313119}, 'lm_rsqs': {'Alpha': 0.5309700521450023, 'Beta': 0.5303717959540357, 'Delta': 0.0883952462650831, 'Ductal': 0.5049625870960767, 'Epsilon': 0.7597662359053344, 'Ngn3 high EP': 0.5709607626498637, 'Ngn3 low EP': 0.43575990380120955, 'Pre-endocrine': 0.33254698128300475}}

拓扑部分

In [ ]:
model_metric_dict = {}
metric_id_list = metrics[metrics["category"] == "topology"]["metric_id"].tolist()
for model_name in model_name_list:
    model_metric = cfe.metric.calculate_metrics(
        fadata,
        metrics=metric_id_list,
        now_model=model_name,
        ref_model="ref"
    )
    model_metric_dict[model_name] = model_metric

df = pd.DataFrame(model_metric_dict).T
df.index=parsed_model_name_list
df

                                isomorphic  edge_flip       him
ref                                    1.0        1.0  1.000000
comp1-python_function                  0.0        0.0  0.272876
state_comp-python_function             0.0        0.4  0.212602
paga-python_function                   0.0        0.0  0.537932
cluster_mst-python_function            0.0        0.0  0.272876
projection_mst-python_function         0.0        0.5  0.578087

F1 score等部分

In [13]:
#映射到里程碑上
F1_dict={}
for i,j in zip(model_name_list,parsed_model_name_list):
    F1_dict[j]=calculate_mapping(new_fadata,grouping='milestones',simplify=True,ref_model= "ref",pred_model= i)
    
F1_dict

{'ref': {'recovery': 1.0, 'relevance': 1.0, 'F1': 1.0},
 'comp1-python_function': {'recovery': 0.13143736204506956,
  'relevance': 0.18840579710144928,
  'F1': 0.1548481513945341},
 'state_comp-python_function': {'recovery': 0.12469512195121951,
  'relevance': 0.09310412381232247,
  'F1': 0.10660854248818853},
 'paga-python_function': {'recovery': 0.34324747725377286,
  'relevance': 0.4402029855447131,
  'F1': 0.38572589191683554},
 'cluster_mst-python_function': {'recovery': 1.0, 'relevance': 1.0, 'F1': 1.0},
 'projection_mst-python_function': {'recovery': 0.4688077857831513,
  'relevance': 0.47219320244981794,
  'F1': 0.47049440430034717}}

In [14]:
df = pd.DataFrame.from_dict(F1_dict, orient='index')
df

                                recovery  relevance        F1
ref                             1.000000   1.000000  1.000000
comp1-python_function           0.131437   0.188406  0.154848
state_comp-python_function      0.124695   0.093104  0.106609
paga-python_function            0.343247   0.440203  0.385726
cluster_mst-python_function     1.000000   1.000000  1.000000
projection_mst-python_function  0.468808   0.472193  0.470494

In [15]:
#映射到分支上
for i in model_name_list:
    print(calculate_mapping(
        new_fadata,
        grouping='branches',
        simplify=True,
        ref_model= "ref",
        pred_model= i
    ))

{'recovery': 1.0, 'relevance': 1.0, 'F1': 1.0}
{'recovery': 0.14285714285714285, 'relevance': 0.272, 'F1': 0.18732782369146006}
{'recovery': 0.19766283756461714, 'relevance': 0.33213589529379006, 'F1': 0.24783344862540782}
{'recovery': 0.4406325169790399, 'relevance': 0.5125292374085532, 'F1': 0.4738693025923582}
{'recovery': 0.5969574010796553, 'relevance': 0.6567236698662998, 'F1': 0.625415927984096}
{'recovery': 0.4270793748156389, 'relevance': 0.43089527349135065, 'F1': 0.42897883842333245}

查看correlation表现

In [16]:

model_metric_dict = {}
metric_id_list = metrics[metrics["category"] == "cell positions"]["metric_id"].tolist()
for model_name in model_name_list:
    model_metric = cfe.metric.calculate_metrics(
        fadata,
        metrics=metric_id_list,
        now_model=model_name,
        ref_model="ref"
    )
    model_metric_dict[model_name] = model_metric

df = pd.DataFrame(model_metric_dict).T
df.index=parsed_model_name_list
df

                                correlation
ref                                1.000000
comp1-python_function              0.197914
state_comp-python_function         0.000000
paga-python_function               0.000000
cluster_mst-python_function        0.000000
projection_mst-python_function     0.000000