In [1]:
import cafe

method_df = cafe.method.scan_method(return_type="dataframe")
method_df.to_csv("methods.csv")
method_df

[09/28/2025 06:08:51] INFO
                                  _____     _ _ ______    _       ______            _
                                 / ____|   | | |  ____|  | |     |  ____|          | |
                                | |     ___| | | |__ __ _| |_ ___| |__  __  ___ __ | | ___  _ __ ___ _ __
                                | |    / _ \ | |  __/ _` | __/ _ \  __| \ \/ / '_ \| |/ _ \| '__/ _ \ '__|
                                | |___|  __/ | | | | (_| | ||  __/ |____ >  <| |_) | | (_) | | |  __/ |
                                 \_____\___|_|_|_|  \__,_|\__\___|______/_/\_\ .__/|_|\___/|_|  \___|_|
                                                                             | |
                                                                             |_|

,name,version,description,wrapper_type,doi,github_url,parameter
latentvelo,latentvelo,0.0.1,LatentVelo,velocity,10.1016/j.crmeth.2023.100581,https://github.com/Spencerfar/LatentVelo,"{'adata': {'name': 'adata', 'default': None, '..."
unitvelo,unitvelo,0.0.1,UniTVelo: temporally unified RNA velocity rein...,velocity,https://doi.org/10.1038/s41467-022-34188-7,https://github.com/StatBiomed/UniTVelo,"{'adata': {'name': 'adata', 'default': None, '..."
velovi,velovi,0.0.1,VeloVI: Deep generative modeling of transcript...,velocity,10.1038/s41592-023-01994-w,https://github.com/yoseflab/velovi,"{'adata': {'name': 'adata', 'default': None, '..."
regvelo,regvelo,0.0.1,regvelo,velocity,10.1101/2024.12.11.627935,https://github.com/theislab/regvelo,"{'adata': {'name': 'adata', 'default': None, '..."
phylovelo,phylovelo,0.0.1,PhyloVelo: Phylogeny-based transcriptomic velo...,velocity,10.1038/s41587-023-01887-5,https://github.com/kunwang34/PhyloVelo,"{'adata': {'name': 'adata', 'default': None, '..."
deepvelo2,deepvelo2,0.0.1,DeepVelo: deep learning extends RNA velocity t...,velocity,10.1186/s13059-023-03148-9,https://github.com/bowang-lab/DeepVelo,"{'adata': {'name': 'adata', 'default': None, '..."
celldancer,celldancer,0.0.1,CellDancer: Estimating Cell-dependent RNA Velo...,velocity,10.1038/s41587-023-01728-5,https://github.com/GuangyuWangLab2021/cellDancer,"{'adata': {'name': 'adata', 'default': None, '..."
veloae,veloae,0.0.1,VeloAE: Representation learning of RNA velocit...,velocity,10.1073/pnas.2105859118,https://github.com/qiaochen/VeloAE,"{'adata': {'name': 'adata', 'default': None, '..."
pyrovelocity,pyrovelocity,0.0.1,PyroVelocity: probabilistic modeling of RNA ve...,velocity,10.1101/2022.09.12.507691,https://github.com/pinellolab/pyrovelocity,"{'adata': {'name': 'adata', 'default': None, '..."
palantir,palantir,0.0.1,Palantir: characterization of cell fate probab...,"[linear, probability, lineage]",10.1038/s41587-019-0068-4,https://github.com/dpeerlab/Palantir,"{'adata': {'name': 'adata', 'default': None, '..."
velovae,velovae,0.0.1,VeloVAE: Bayesian Inference of RNA Velocity fr...,velocity,10.1101/2022.07.08.499381,https://github.com/welch-lab/VeloVAE,"{'adata': {'name': 'adata', 'default': None, '..."
comp1,comp1,0.0.1,"Comp1: baseline for linear wrapper, extract an...",linear,NaN,NaN,"{'adata': {'name': 'adata', 'default': None, '..."
deepvelo,deepvelo,0.0.1,DeepVelo: Single-cell transcriptomic deep velo...,velocity,10.1126/sciadv.abq3745,https://github.com/gersteinlab/DeepVelo,"{'adata': {'name': 'adata', 'default': None, '..."
sctc,sctc,0.0.1,SCTC: single-Cell Transcriptional Complexity,linear,10.1093/nar/gkae340,https://github.com/hailinphysics/sctc,"{'adata': {'name': 'adata', 'default': None, '..."
paga,paga,0.0.1,PAGA: partition-based graph abstraction,branch,10.1186/s13059-019-1663-x,https://github.com/theislab/paga,"{'adata': {'name': 'adata', 'default': None, '..."
cytotrace2,cytotrace2,0.0.1,Cytotrace2: cellular potency categories and ab...,linear,10.1101/2024.03.19.585637,https://github.com/digitalcytometry/cytotrace2,"{'adata': {'name': 'adata', 'default': None, '..."
velocity,veloae,0.0.1,VeloAE: Representation learning of RNA velocit...,velocity,10.1073/pnas.2105859118,https://github.com/qiaochen/VeloAE,"{'adata': {'name': 'adata', 'default': None, '..."
cell2fate,Cell2fate,0.0.1,Cell2fate infers RNA velocity modules to impro...,velocity,10.1038/s41592-025-02608-3,https://github.com/BayraktarLab/cell2fate,"{'adata': {'name': 'adata', 'default': None, '..."
scvelo,scvelo,0.0.1,scVelo: RNA velocity generalized through dynam...,velocity,10.1038/s41587-020-0591-3,https://github.com/theislab/scvelo,"{'adata': {'name': 'adata', 'default': None, '..."
dynamo,dynamo,0.0.1,Dynamo: Mapping Transcriptomic Vector Fields o...,velocity,10.1016/j.cell.2021.12.045,https://github.com/aristoteleo/dynamo-release,"{'adata': {'name': 'adata', 'default': None, '..."

后续代码由于本机网络原因, 无法运行, 需要在windows(D:\2.code\cfe\cfe_methods_citations&stars.ipynb )或Google Colab上运行

In [ ]:
# import pandas as pd
# import numpy as np
# import re
# import time
# import requests
# from scholarly import scholarly
# from tqdm.auto import tqdm


# def get_citations_and_stars(df: pd.DataFrame) -> pd.DataFrame:
#     citations = []
#     stars = []

#     for _, row in tqdm(df.iterrows(), total=df.shape[0], desc="Fetching data"):
#         # --- 1. get citation num ---
#         doi = row.get("doi")
#         citation_count = np.nan
#         if pd.notna(doi):
#             try:
#                 search_query = scholarly.search_single_pub(doi)
#                 if "num_citations" in search_query:
#                     citation_count = search_query["num_citations"]
#                 time.sleep(3) # a small delay
#             except Exception as e:
#                 print(f"Could not fetch citation for DOI {doi}: {e}")
#         citations.append(citation_count)

#         # --- 2. get github star ---
#         github_url = row.get("github_url")
#         star_count = np.nan
#         if pd.notna(github_url):
#             match = re.search(r"github\.com/([^/]+)/([^/]+)", github_url) # regex for extracting owner/repo
#             if match:
#                 owner, repo = match.groups()
#                 api_url = f"https://api.github.com/repos/{owner}/{repo}"
#                 try:
#                     response = requests.get(api_url)
#                     if response.status_code == 200:
#                         data = response.json()
#                         star_count = data.get("stargazers_count", np.nan)
#                     else:
#                         print(f"GitHub API request failed for {github_url} with status: {response.status_code}")
#                 except Exception as e:
#                     print(f"Could not fetch stars for {github_url}: {e}")
#         stars.append(star_count)

#     result_df = pd.DataFrame([citations, stars], index=["citations", "stars"]).T
#     result_df.index = df.index
#     result_df = result_df.astype("Int64")
#     return result_df

# method_df = pd.read_csv("methods.csv", index_col=0)
# citations_and_stars_df = get_citations_and_stars(method_df.copy())
# citations_and_stars_df.to_csv("citations_and_stars.csv")
# citations_and_stars_df

In [3]:
import pandas as pd

citations_and_stars_df = pd.read_csv("citations_and_stars.csv", index_col=0)
citations_and_stars_df = citations_and_stars_df.astype("Int64")
citations_and_stars_df

              citations  stars
latentvelo           30     26
unitvelo           <NA>     26
velovi               97     40
regvelo               5     56
phylovelo            46     43
deepvelo2            51     46
celldancer           90     70
veloae               57     28
pyrovelocity         23     47
palantir            674    267
velovae              35     35
comp1              <NA>   <NA>
deepvelo             74     14
sctc                  5      5
paga               1609    227
cytotrace2           56    171
velocity             57     28
cell2fate             4     79
scvelo             2605    467
dynamo              385    472